### ISSUE TITLE
[Bug] Crash on Plugin Load/Reload when The Game Is Running

### ISSUE THREAD

**Issue by GreenComfyTea** [Fexty12573/SharpPluginLoader#21]
## Describe The Bug
 When the game is running, an attempt to copy-paste a new .dll or overwrite an existing .dll leads to a crash. I assume it is because the copying process locks the files, and the file change event is fired before the files are unlocked, which results in SharpPluginLoader attempting to read locked files.

The crash happens regardless on what is writting the dll:
1. Manually copying -> sometimes crash;
2. Building directly into `\Monster Hunter World\nativePC\plugins\CSharp\` -> crash;
3. Running the command `xcopy "$(OutDir)" "D:\Programs\Steam\steamapps\common\Monster Hunter World\nativePC\plugins\CSharp\MHWTeaOverlay" /s /i /y` as a post-build event -> crash.

SharpPluginLoader and the plugin itself are working normally in almost all other situations. (Except for ImGui having the viewport of 1920x1080 instead of 2880x1620 so it cuts in the middle of screen, but I haven't looked into it yet, it might be because i have super-sampled resolution).

**The Exception:**
```
[Core] Unhandled exception: IOException: The process cannot access the file 'D:\Programs\Steam\steamapps\common\Monster Hunter World\nativePC\plugins\CSharp\MHWTeaOverlay\MHWTeaOverlay.dll' because it is being used by another process., Stacktrace:
	at CreateFile (:0:0)
	at Open (:0:0)
	at .ctor (:0:0)
	at IsManageAssembly (:0:0)
	at <.ctor>b__12_2 (:0:0)
	at NotifyFileSystemEventArgs (:0:0)
	at ParseEventBufferAndNotifyForEach (:0:0)
	at ReadDirectoryChangesCallback (:0:0)
	at <StartRaisingEvents>b_85_0 (:0:0)
	at Invoke (:0:0)
	at System.Threading.IThreadPoolWorkItem.Execute (:0:0)
	at Dispatch (:0:0)
	at WorkerThreadStart (:0:0)
```

## To Reproduce
1. Place the plugin .dll into `\Monster Hunter World\nativePC\plugins\CSharp`;
5. Launch the game, wait until Main Menu appears;
6. Rebuild the plugin, copy-overwrite the existing plugin .dll with a new one in `\Monster Hunter World\nativePC\plugins\CSharp`;
7. Crash.

**Alternatively:**
1. Launch the game, wait until Main Menu appears;
2. Place the plugin .dll into `\Monster Hunter World\nativePC\plugins\CSharp`;
3. Crash.

## Expected Behavior
No crash. SharpPluginLoader should handle the exception, wait until the copy process is done and the files are unlocked before attempting to load/reload the plugin.

## Priority
Suggested P3 Priority. The issue directly affects plugin development but is circumvented by relaunching the game each time. The issue doesn't affect how plugins work and perform.

## Screenshots/Video
**[Video](https://streamable.com/5ddfza)**

## PC Specs
 - `Motherboard`**: Asus ROG Strix Z390-H Gaming**
 - `CPU`**: Intel Core i9-9900k**
 - `RAM`**: 32 GB 3200MHz**
 - `GPU`**: Nvidia GeForce RTX 3090 Ti**
 - `System and Game SSD`**: Samsung SSD 970 EVO Plus NVMe M.2 1TB**
 - `Plugin Repo SSD`**: Western Digital Blue SATA M.2 2280 2TB**

## Environment
 - `OS`: **Window 10 Enterprise Version 22H2 (OS Build 19045.3996)**
 - `Monster Hunter: World`: **v15.21.00**
 - `SharpPluginLoader`: **v0.0.3.1**
 - `Nvidia Drivers`**: v551.23**

## Game Display Settings
 - `DirectX 12 API`**: On**
 - `Screen Mode`**: Borderless Window**
 - `Resolution Settings`**: 2880x1620** (Supersampled down to 1920x1080)
 - `Aspect Ratio`**: Wide (16:9)**
 - `Nvidia DLSS`**: Off**
 - `FidelityFX CAS + Upscaling`**: Off**
 - `Frame Rate`**: No Limit**
 - `V-Sync`**: On**

## Game Advanced Graphics Settings
 - `Image Quality`**: High**
 - `Texture Quality`**: High Resolution Texture Pack**
 - `Ambient Occlusion`**: High**
 - `Volume Rendering Quality`**: Highest**
 - `Shadow Quality`**: High**
 - `Capsule AO`**: On**
 - `Contact Shadows`**: On**
 - `Anti-Aliasing`**: Off**
 - `LOD Bias`**: High**
 - `Max LOD Level`**: No Limit**
 - `Foliage Sway`**: On**
 - `Subsurface Scattering`**: On**
 - `Screen Space Reflection`**: On**
 - `Anisotropic Filtering`**: Highest**
 - `Water Reflection`**: On**
 - `Snow Quality`**: High**
 - `SH Diffuse Quality`**: High**
 - `Dynamic Range`**: 64-bit**
 - `Motion Blur`**: On**
 - `DOF (Depth of Field)`**: On**
 - `Vignette Effects`**: Normal**
 - `Z-Prepass`**: On**

## Mods and External Tools:
- [RTSS Overlay v7.3.4](https://www.guru3d.com/page/rivatuner-rtss-homepage/)
 - [Reshade 6.0.0](https://reshade.me/) with SMAA.fx
 - [Stracker's Loader v3.0.1](https://www.nexusmods.com/monsterhunterworld/mods/1982)
 - [Performance Booster and Plugin Extender v1.3](https://www.nexusmods.com/monsterhunterworld/mods/3473)
 - [HunterPie v2.10.0.134](https://www.nexusmods.com/monsterhunterrise/mods/181)
 - [HelloWorld (an overlay that shows lots and lots of stuff) v10.4](https://www.nexusmods.com/monsterhunterworld/mods/142)
 - [Bow Spread Pattern Fix v1.0](https://www.nexusmods.com/monsterhunterworld/mods/6914)
 - [Tic Rate Fix v1.0](https://www.nexusmods.com/monsterhunterworld/mods/3474)
 - [Guiding Lands Gathering Indicator v1.12.11.01](https://www.nexusmods.com/monsterhunterworld/mods/1986)
 - [Gems Sorted by Name (Alphabetized Gems) v1.6.1](https://www.nexusmods.com/monsterhunterworld/mods/2364)
 - [Reshade Hook v1.0](https://www.nexusmods.com/monsterhunterworld/mods/7015)
 - [Endemic Quality (Iceborne Edition) v1.4](https://www.nexusmods.com/monsterhunterworld/mods/2137)
 - [Remove censor bad word banned word filter v1.0](https://www.nexusmods.com/monsterhunterworld/mods/6956)
 - [Monster Weakness Icon Indicator for Iceborne (Hi-Res) vFinal](https://www.nexusmods.com/monsterhunterworld/mods/1938)
 - [Cuter Handler Face Model (Post-Iceborne) aka Make Handler Cuter Again v3.0](https://www.nexusmods.com/monsterhunterworld/mods/1914)

## Additional Context
[Plugin Repo](https://github.com/GreenComfyTea/MHW-Tea-Overlay)

Nonetheless, I am very happy with the ability of making plugins in C#. Thank you for creating such a wonderful tool!❤️

**Comment by Fexty12573** [comment]
Hi! Thank you very much for the very elaborate report. I have noticed this again before but haven't gotten around to actually fixing it yet.
I'll try to make a basic workaround for now.

**Comment by Fexty12573** [comment]
Pushed a fix in 02972748cb1f9f18a283967d3b4ca82f87ad0010. This will be part of 0.0.4, which most likely will release within the next couple of days.

PS: Awesome plugin, this is exactly the kind of stuff I envisioned when first creating this. Version 0.0.4 will also have support for loading arbitrary textures/images, so you'll be able to make the overlay look nicer 😄

**Comment by GreenComfyTea** [comment]
The fix works, thanks! 👍

PS: I guess our meet was destined. Was waiting for either Lua or C# framework to create an overlay mod for World that runs inside the game and not as an external tool, as I did for Rise. As soon as noticed SPL in like december, I had my eyes wide open! 👀

PPS: I already can draw images thou, ImGui.GetBackgroundDrawList().AddImage() is there 🤔

**Comment by Fexty12573** [comment]
Regarding `ImGui.GetBackgroundDrawList().AddImage()`, yes, that's the intention after all. What I meant by "loading textures/images" is the process of actually creating the relevant Direct3D resources. That function expects an `ID3D11ShaderResourceView*` when running in DX11 and a `D3D12_GPU_DESCRIPTOR_HANDLE` when running in DX12. 

*Sure* you could technically pull in the entirety of Silk.NET or something similar and start making graphics api calls yourself but... that's honestly a pain.

The API aims to abstract away all of the low level Direct3D calls in a graphics-api agnostic manner. I.e. you will not have to worry about if the game is running in DX11 or 12 mode and you can just call a `LoadTexture` function to load any .dds/.png/.jpg and pass that to the `ImGui.*Image` functions.

PPPS: Please do!

**Comment by GreenComfyTea** [comment]
Fair enough! ;3
