### ISSUE TITLE
Loader not running

### ISSUE THREAD

**Issue by Renaclock** [Fexty12573/SharpPluginLoader#28]
Need some help.
I've been trying to use [Dynamic Camera Distance and Zoom](https://www.nexusmods.com/monsterhunterworld/mods/7134) but the loader doesn't seem to be running with the game.
winmm.dll is at the root folder(with .exe) and CSharp folder is inside "nativePC/plugins".
No console pop up,no log file generated.
I have .NET 8.0.2 installed and also tried  8.0.0 but no luck.

**Comment by Fexty12573** [comment]
Were you able to solve this?
