### ISSUE TITLE
[Bug] Stutters on SPL v.0.0.4.1

### ISSUE THREAD

**Issue by GreenComfyTea** [Fexty12573/SharpPluginLoader#35]
## Describe The Problem

I have received a number of reports about stuttering/fps pacing. The longer they played the worse were the stutters. Downgrading to SPL v0.0.4 seems to fix the issue.

<details>
<summary>Screenshot 1</summary>

![image](https://github.com/Fexty12573/SharpPluginLoader/assets/30152047/7ed53dcc-0ad0-4d5b-ac0d-114f41318578)
</details>

<details>
<summary>Screenshot 2</summary>

![image](https://github.com/Fexty12573/SharpPluginLoader/assets/30152047/687ea35a-b031-4937-aca2-4dad384bb82d)
</details>

<details>
<summary>Screenshot 3</summary>

![image](https://github.com/Fexty12573/SharpPluginLoader/assets/30152047/9f2be3a4-1731-48dc-9c83-a86254987fe1)
</details>

<details>
<summary>Screenshot 4</summary>

![image](https://github.com/Fexty12573/SharpPluginLoader/assets/30152047/c281a536-7650-4998-8221-df625f0360a5)
</details>

<details>
<summary>Screenshot 5</summary>

![image](https://github.com/Fexty12573/SharpPluginLoader/assets/30152047/cdcf1534-1038-482b-9422-ac83fee078f7)
</details>

## To Reproduce
...

## Expected Behavior
No stutters.

## Priority
Suggested P2 Priority. The game is unplayable for some players.

**Comment by Fexty12573** [comment]
Yikes. Could you ask people to try 0.0.4.1 but have `PrimitiveRenderingEnabled` set to `false` in the config? I didn't change many things in 0.0.4.1. And if possible let me know if there are other people that *don't* have stutters with 0.0.4.

**Comment by GreenComfyTea** [comment]
Sure will!

There is 1 more person who tried v0.0.4, thou on v0.0.4.1 they encountered the stutters only once, so they are not a reliable example.

<details>
<summary>Screenshot</summary>

![image](https://github.com/Fexty12573/SharpPluginLoader/assets/30152047/165387e6-6a03-439d-85d6-58cc4c51219d)

</details>

**Comment by Fexty12573** [comment]
Hmmm ok might be some sort of memory leak then. I did quite heavily revamp that system with 0.0.4.1. Will check when I get home.

**Comment by Fexty12573** [comment]
Actually it's probably the GC. I pin a lot of stuff which most likely results in fragmentation so the GC has longer and longer. I'll probably change these arrays to be native memory instead of managed Lists. I will have to make a 0.0.4.2 release anyway so this works.

**Comment by GreenComfyTea** [comment]
There was 1 another person who was saying that alt-tabbing was increasing RAM each time. I couldn't replicate it + the person was quite, so it might have been just a troll.

**Comment by Fexty12573** [comment]
I pushed a potential fix for this in f921f36f9da580c879af2a082375cfd944e3dbb4. If possible, could you test this?

**Comment by GreenComfyTea** [comment]
I would if I could. But on my PC I have 0 issues. Probably, my PC just tanks it. I can only ask others to try it out.

**Comment by GreenComfyTea** [comment]
>There is 1 more person who tried v0.0.4, thou on v0.0.4.1 they encountered the stutters only once, so they are not a reliable example.

This person says no stutters.

<details>
<summary>Screenshot</summary>

![image](https://github.com/Fexty12573/SharpPluginLoader/assets/30152047/94286a80-d9fc-4970-a126-3f69c8b56360)
</details>

**Comment by Fexty12573** [comment]
Hmmm. I think I'll just make a 0.0.5 release. Didn't change much in that so it shouldn't require an update on your end.

**Comment by Fexty12573** [comment]
Can I close this? Or do the stutters persist?

**Comment by GreenComfyTea** [comment]
I haven't received any reports about the stutters still being present. You can close it.
