### ISSUE TITLE
Game updated,and the plugin seems like not working anymore

### ISSUE THREAD

**Issue by fre0601** [Fexty12573/SharpPluginLoader#41]

**Comment by Fexty12573** [comment]
Fixed with 0.0.6.1

**Comment by GreenComfyTea** [comment]
Whatever you have changed for v0.0.6.1, it isn't included in the repo, so building SPL manually still results in a not working build. 😢 
(I was also hoping you would include in the release the fix for the crash that happens due to font rebuilding when going back to main menu from a session 😢).

**Comment by Fexty12573** [comment]
0.0.7 is not really ready for release so 0.0.6.1 is still based on 0.0.6 just with that one fix. The fix is to change the build number in the window title string in `D3DModule.h`.
