### ISSUE TITLE
F9 Key does nothing

### ISSUE THREAD

**Issue by grmycaire** [Fexty12573/SharpPluginLoader#42]
Using the F9 key does nothing. I tried binding other key but same issue. I'm using the lastes version of both SharpPlugin and Stracker's Loader.
I'ts like SharpPlugin is not working at all.
I see nothing in Stracker's log and I have .NET desktop runtine V8.0.6 installed.

**Comment by Fexty12573** [comment]
Is there anything in `nativePC/plugins/CSharp/Loader/SharpPluginLoader.log`?

**Comment by grmycaire** [comment]
There is 4 files but no .log file. I Assume it's because SharpPlugin does not even start. That's Weird because everything is up to date and I already managed to get it running in the past with old versions.

**Comment by Souls02** [comment]
where I have to put the folder [SharpPluginLoader 0.0.6.1]

**Comment by grmycaire** [comment]
I think you're not in the wrong place ?

> where I have to put the folder [SharpPluginLoader 0.0.6.1]

You have to copy the nativePC folder and winmm.dll into the Monster Hunter root folder.

**Comment by Fexty12573** [comment]
> There is 4 files but no .log file. I Assume it's because SharpPlugin does not even start. That's Weird because everything is up to date and I already managed to get it running in the past with old versions.

If you set the log level (in loader-config.json) to `INFO`/`DEBUG` is there any console that pops up? Do you have winmm.dll next to the game's exe?

**Comment by grmycaire** [comment]
Yes I confirm you I have the winmm.dll next to the exe and I've already set log level to INFO. The console is showing up at game start.
I'll set log level to debug, maybe I'll have more information about the problem.

**Comment by grmycaire** [comment]
I found the solution. My game was running as administrator and that was the issue. When running as non admin, everything in working like a charm.
Is the plugin intended to work only when the game is running as non admin ?
I mark this issue as closed since my problem is solved. I hope it will be useful.

**Comment by Fexty12573** [comment]
> Is the plugin intended to work only when the game is running as non admin ?

No, it isn't. But most likely Windows has some special behavior for `winmm.dll` when running in administrator, which causes it to not get loaded. Thanks a lot for posting the solution here! I have had other peopl report this issue and I could not figure out what was causing it. 👍
