### ISSUE TITLE
where I have to put the folder SharpPluginLoader 0.0.6.1

### ISSUE THREAD

**Issue by Souls02** [Fexty12573/SharpPluginLoader#43]
![Anotación 2024-07-04 133905](https://github.com/Fexty12573/SharpPluginLoader/assets/174709383/cb654154-ea0d-4e9f-a4d6-8690647ea7be)
![Anotación 2024-07-04 133846](https://github.com/Fexty12573/SharpPluginLoader/assets/174709383/3e42da72-2a0f-447c-a6a3-ae77c32af44d)

**Comment by Fexty12573** [comment]
https://fexty12573.github.io/SharpPluginLoader/Install/Installation.html
