### ISSUE TITLE
Game Version 15.23 Error

### ISSUE THREAD

**Issue by emersondonizeti** [Fexty12573/SharpPluginLoader#48]
After updating MH yesterday, I'm getting the following error: 

![image](https://github.com/user-attachments/assets/b779cde9-c18d-4da1-ae95-03739dc96757)

**Comment by SnoozeBuu** [comment]
same

**Comment by sebosovil** [comment]
same

**Comment by kabedonn** [comment]
same

**Comment by Joaopedrocarvalho12** [comment]
same

**Comment by RealBotuna** [comment]
Sorry for the annoyance.
Will the update take weeks? or is it near done? Just curious.

**Comment by Fexty12573** [comment]
The update is done, I've just been too lazy to make a release. I'll do it sometime today.

**Comment by RealBotuna** [comment]
Thank you so much for you efforts it's really appreciated! <3

**Comment by Fexty12573** [comment]
The newest release for 15.23 can be found here: https://github.com/Fexty12573/SharpPluginLoader/releases/tag/0.0.7.1
